// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3eL2v1cz2Oekxvjwot8aXdPH_UB-tns8',
    appId: '1:207138036977:web:b19e06e15563d6a8221d50',
    messagingSenderId: '207138036977',
    projectId: 'jobaajtask',
    authDomain: 'jobaajtask.firebaseapp.com',
    storageBucket: 'jobaajtask.firebasestorage.app',
    measurementId: 'G-82FQ1RWRP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbM_tdVdbMog6paX9C9qEfP5aRradNlyI',
    appId: '1:207138036977:android:12f844a088fa7f8b221d50',
    messagingSenderId: '207138036977',
    projectId: 'jobaajtask',
    storageBucket: 'jobaajtask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWQEnNFh_09qmu-21atxxeu_zVXm8nNE',
    appId: '1:207138036977:ios:165d1b76cd49a754221d50',
    messagingSenderId: '207138036977',
    projectId: 'jobaajtask',
    storageBucket: 'jobaajtask.firebasestorage.app',
    iosBundleId: 'com.example.firstApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWQEnNFh_09qmu-21atxxeu_zVXm8nNE',
    appId: '1:207138036977:ios:165d1b76cd49a754221d50',
    messagingSenderId: '207138036977',
    projectId: 'jobaajtask',
    storageBucket: 'jobaajtask.firebasestorage.app',
    iosBundleId: 'com.example.firstApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3eL2v1cz2Oekxvjwot8aXdPH_UB-tns8',
    appId: '1:207138036977:web:8d7053cf8f007f97221d50',
    messagingSenderId: '207138036977',
    projectId: 'jobaajtask',
    authDomain: 'jobaajtask.firebaseapp.com',
    storageBucket: 'jobaajtask.firebasestorage.app',
    measurementId: 'G-108W92SNQE',
  );

}